### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by jongh222** [genforce/genforce#10]
(genforce) C:\Users\A\Desktop\genforce-master>python synthesize.py stylegan_ffhq1024
Building generator for model `stylegan_ffhq1024` ...
Finish building generator.
Loading checkpoint from `checkpoints\stylegan_ffhq1024.pth` ...
Traceback (most recent call last):
  File "synthesize.py", line 147, in <module>
    main()
  File "synthesize.py", line 108, in main
    checkpoint = torch.load(checkpoint_path, map_location='cpu')
  File "C:\Users\A\anaconda3\envs\genforce\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\A\anaconda3\envs\genforce\lib\site-packages\torch\serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

HOW??

**Comment by ShenYujun** [comment]
Could you please try PyTorch 1.5 or above? We have never seen this error before :(

**Comment by jongh222** [comment]
> Could you please try PyTorch 1.5 or above? We have never seen this error before :(

I tried, but it didn't change...

**Comment by limbo0000** [comment]
Hi @jongh222, Could you please try to load any checkpoint file on your platform? We didn't debug it on windows before. For instance, you can load the weight of pre-trained resnet50.
