### ISSUE TITLE
Error in running stylegan_demo

### ISSUE THREAD

**Issue by learnthehardway93** [genforce/genforce#2]
Hi,

Running `python -m torch.distributed.launch --nproc_per_node=1 train.py ./configs/stylegan_demo.py --work_dir work_dirs/stylegan_demo/ --launcher="pytorch" ` throughs error when doing optimizer.step(). Below is the trace. Could you help fix this?

`
[2020-10-12 20:14:25][INFO] Rebuild the dataset at iter 000001 (lod 3.000000).
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    main()
  File "train.py", line 113, in main
    runner.train()
  File "/home/ubuntu/efs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/home/ubuntu/efs/genforce/runners/stylegan_runner.py", line 45, in train_step
    self.optimizers['discriminator'].step()
  File "/home/ubuntu/anaconda3/envs/pytorch_py3.6/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 51, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_py3.6/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/efs/genforce/runners/optimizer.py", line 193, in step
    state['exp_avg'] = torch.zeros_like(p, memory_format=torch.preserve_format)
TypeError: zeros_like() received an invalid combination of arguments - got (Parameter, memory_format=torch.memory_format), but expected one of:
 * (Tensor input, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Tensor input, bool requires_grad)
      didn't match because some of the keywords were incorrect: memory_format

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_py3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/pytorch_py3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/pytorch_py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/pytorch_py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/pytorch_py3.6/bin/python', '-u', 'train.py', '--local_rank=0', './configs/stylegan_demo.py', '--work_dir', 'work_dirs/stylegan_demo/', '--launcher=pytorch']' returned non-zero exit status 1.
`

**Comment by justimyhxu** [comment]
Could you report the version of the PyTorch? I recommend PyTorch1.5 for this codebase.

**Comment by learnthehardway93** [comment]
Was using Pytorch-1.3, cudatoolkit-10.0, torchvision-0.4 earlier and it was causing issues. Works fine with Pytorch-1.5, cudatoolkit-10.1, torchvision-0.6. 

Just for information, there seems to be errors with cudatoolkit-10.2

Thanks and closing the issue.
