### ISSUE TITLE
GPUs training error: Logger `logger` has already existed!

### ISSUE THREAD

**Issue by WangQinghuCS** [genforce/genforce#21]
Hi, thanks for your code!
When I train my model on 4 gpus, I come across the error: "Logger `logger` has already existed!"
Do you know how to fix it?

**Comment by ShenYujun** [comment]
How many loggers have you used? If you need to use more than one logger, please use a different name for the second logger.

**Comment by ysig** [comment]
I have the same problem.

**Comment by ShenYujun** [comment]
Can you reproduce this error when using `GPU=1`?

**Comment by WangQinghuCS** [comment]
add the "self.logger.propagate = 0" in the class Logger of utils/logger.py  will solve it.

**Comment by ysig** [comment]
@WangQinghuCS 
I did it and I again get:

```
Logger `logger` has already existed!
Please use another name, or otherwise the messages from these two logger may be mixed up.
Killing subprocess 74916
Killing subprocess 74917
Killing subprocess 74918
Killing subprocess 74919
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/genforce/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/miniconda3/envs/genforce/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubuntu/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubuntu/iniconda3/envs/genforce/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/miniconda3/envs/genforce/bin/python', '-u', './train.py', '--local_rank=3', 'stylegan2_synthetic_512.py', '--work_dir', 'work_dirs/experiment', '--launcher=pytorch']' returned non-zero exit status 1.
```

Now I am thinking this may not be the problem. Do you know where I can see the error?

**Comment by ysig** [comment]
@ShenYujun 
When running with GPU=1 I get:
```
Logger `logger` has already existed!
Please use another name, or otherwise the messages from these two logger may be mixed up.
Killing subprocess 75689
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/genforce/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/miniconda3/envs/genforce/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ilan/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubuntu/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubuntu/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ilan/miniconda3/envs/genforce/bin/python', '-u', './train.py', '--local_rank=0', 'stylegan2_synthetic_512.py', '--work_dir', 'work_dirs/experiment', '--launcher=pytorch']' returned non-zero exit status 1.
```
But I can't see the specific error...

**Comment by WangQinghuCS** [comment]
@ysig  you can comment  set a break in the  in the class Logger of utils/logger.py and see the handlers of the logger. And you can try to comment directly
![image](https://user-images.githubusercontent.com/33517563/114155180-c9171300-9953-11eb-9752-8c2c9bb6d665.png), may be solve your problem.

**Comment by WangQinghuCS** [comment]
@ysig  By the way, where do you add "self.logger.propagate = 0"? I do it like this
![image](https://user-images.githubusercontent.com/33517563/114155468-1d21f780-9954-11eb-87e0-fb4c54a8c1d1.png)

**Comment by ysig** [comment]
It works! I suggest you add this as a command line argument (--ignore-logger-collision), so you make it more usable.
Thanks a lot :)
