### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by ysig** [genforce/genforce#22]
Hi,

I notice that genforce caches all my loaded images into memory, creating a memory overload of > 60 GB which causes a memory error.
I am using a dataset of 9M images and of course there is no need to cache all of them to the cpu memory.
Could you suggest a workaround?

Thank you,
Y

**Comment by ysig** [comment]
After searching a lot inside the code the issue is not related with pin_memory on the dataloader but with the private method __generate_indices__ of the distributed sampler.
It is a problem even if the dataset contains 500K images.

**Comment by ysig** [comment]
Even in the case of 200K images, I get the error:
```
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/media/ilan/deepcomics/libs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/media/ilan/deepcomics/libs/genforce/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/ilan/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'SynthesisModule' object has no attribute 'lod'
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/media/ilan/deepcomics/libs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/media/ilan/deepcomics/libs/genforce/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/ilan/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'SynthesisModule' object has no attribute 'lod'
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/media/ilan/deepcomics/libs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/media/ilan/deepcomics/libs/genforce/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/ilan/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))

```

**Comment by limbo0000** [comment]
Hi @ysig, 

Thanks for your issue. Could you please set the data.repeat as a small number like 10? The variable repeats the indices of the whole dataset multiple times, requiring large memory.

**Comment by ysig** [comment]
Thank you, I will try it.
But what about the lod error: https://github.com/genforce/genforce/issues/22#issuecomment-822055446  ?

Thanks

**Comment by ShenYujun** [comment]
The `lod` variable is defined [here](https://github.com/genforce/genforce/blob/30387208f662284f2fa30b646955d94cd9e8fb49/models/stylegan_generator.py#L364). My guess is that you are using StyleGAN2 generator. Since StyleGAN2 does not require progressive training, `lod` will be of no use in the generator and hence not well-defined.
