### ISSUE TITLE
AttributeError: 'SynthesisModule' object has no attribute 'lod'

### ISSUE THREAD

**Issue by ysig** [genforce/genforce#24]
I get the following error when running Stylegan2 on my dataset of around 200K images:

```
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/home/libs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/home/libs/genforce/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'SynthesisModule' object has no attribute 'lod'
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/home/libs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/home/libs/genforce/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'SynthesisModule' object has no attribute 'lod'
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/home/libs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/home/libs/genforce/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
```

I have the following config:

```
# python3.7
"""Configuration for training StyleGAN on FF-HQ (1024) dataset.

All settings are particularly used for one replica (GPU), such as `batch_size`
and `num_workers`.
"""

runner_type = 'StyleGANRunner'
gan_type = 'stylegan2'
resolution = 512
batch_size = 4
val_batch_size = 16
total_img = 25000_000

# Training dataset is repeated at the beginning to avoid loading dataset
# repeatedly at the end of each epoch. This can save some I/O time.
DATA = '/media/ilan/DeepFakes/synthetic-experiment/data_backup'
data = dict(
    num_workers=4,
    repeat=500,
    train=dict(root_dir=DATA, resolution=resolution, mirror=0.5),
    val=dict(root_dir=DATA, resolution=resolution),
    #train=dict(root_dir='data/ffhq.zip', data_format='zip',
    #           resolution=resolution, mirror=0.5),
    #val=dict(root_dir='data/ffhq.zip', data_format='zip',
    #         resolution=resolution),
)

controllers = dict(
    RunningLogger=dict(every_n_iters=10),
    ProgressScheduler=dict(
        every_n_iters=1, init_res=8, minibatch_repeats=4,
        lod_training_img=600_000, lod_transition_img=600_000,
        batch_size_schedule=dict(res4=64, res8=32, res16=16, res32=8),
    ),
    Snapshoter=dict(every_n_iters=500, first_iter=True, num=200),
    FIDEvaluator=dict(every_n_iters=5000, first_iter=True, num=50000),
    Checkpointer=dict(every_n_iters=5000, first_iter=True),
)

modules = dict(
    discriminator=dict(
        model=dict(gan_type=gan_type, resolution=resolution),
        lr=dict(lr_type='FIXED'),
        opt=dict(opt_type='Adam', base_lr=1e-3, betas=(0.0, 0.99)),
        kwargs_train=dict(),
        kwargs_val=dict(),
    ),
    generator=dict(
        model=dict(gan_type=gan_type, resolution=resolution),
        lr=dict(lr_type='FIXED'),
        opt=dict(opt_type='Adam', base_lr=1e-3, betas=(0.0, 0.99)),
        kwargs_train=dict(w_moving_decay=0.995, style_mixing_prob=0.9,
                          trunc_psi=1.0, trunc_layers=0, randomize_noise=True),
        kwargs_val=dict(trunc_psi=1.0, trunc_layers=0, randomize_noise=False),
        g_smooth_img=10_000,
    )
)

loss = dict(
    type='LogisticGANLoss',
    d_loss_kwargs=dict(r1_gamma=10.0),
    g_loss_kwargs=dict(),
)
```

which I run through:

```
GPUS=4
CONFIG=stylegan2_synthetic_512.py
WORK_DIR=work_dirs/experiment
./scripts/dist_train.sh ${GPUS} ${CONFIG} ${WORK_DIR}
```

**Comment by ShenYujun** [comment]
StyleGAN2 does not need the `lod` variable for progressive training. Could you please simply try to comment out all codes related to `lod` and also comment out the `ProgressScheduler` in your configuration? It should not affect the training pipeline.

**Comment by ysig** [comment]
@ShenYujun Your comment fixed the error, but I still have another one:
```
[2021-04-25 11:28:23][INFO] Start training.
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/media/ilan/deepcomics/libs/genforce/runners/base_runner.py", line 277, in train
    assert self.total_iters > 0
AssertionError
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/home/libs/genforce/runners/base_runner.py", line 277, in train
    assert self.total_iters > 0
AssertionError
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/miniconda3/envs/genforce/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 6077) is killed by signal: Terminated. 
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/media/deepcomics/libs/genforce/runners/base_runner.py", line 277, in train
    assert self.total_iters > 0
AssertionError

```

**Comment by ShenYujun** [comment]
In StyleGAN, which requires progressive training, the `total_iters` is computed in `ProgressScheduler` based on `total_img`. Since StyleGAN2 does not rely on progressive training, please try to set `total_iters` as `total_img / batch_size / num_gpus` in the configuration file.

**Comment by ysig** [comment]
I did this but I have again another error:

```
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/home/libs/genforce/runners/base_runner.py", line 287, in train
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/home/libs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/home/libs/genforce/runners/stylegan_runner.py", line 34, in train_step
    self.train_step(data_batch, **train_kwargs)
  File "/home/genforce/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'SynthesisModule' object has no attribute 'lod'
    type(self).__name__, name))
AttributeError: 'SynthesisModule' object has no attribute 'lod'
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/home/libs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/home/libs/genforce/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'SynthesisModule' object has no attribute 'lod'
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/home/libs/genforce/runners/base_runner.py", line 287, in train
    self.train_step(data_batch, **train_kwargs)
  File "/home/libs/genforce/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/miniconda3/envs/genforce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'SynthesisModule' object has no attribute 'lod'

```
My config is:
```
# python3.7
"""Configuration for training StyleGAN on FF-HQ (1024) dataset.

All settings are particularly used for one replica (GPU), such as `batch_size`
and `num_workers`.
"""

runner_type = 'StyleGANRunner'
gan_type = 'stylegan2'
resolution = 512
batch_size = 4
val_batch_size = 16
total_img = 25000_000
num_gpus = 4
total_iters = total_img / batch_size / num_gpus

# Training dataset is repeated at the beginning to avoid loading dataset
# repeatedly at the end of each epoch. This can save some I/O time.
DATA = '/media/ilan/DeepFakes/synthetic-experiment/data_backup'
data = dict(
    num_workers=4,
    repeat=4,
    train=dict(root_dir=DATA, resolution=resolution, mirror=0.5, data_format='rdir'),
    val=dict(root_dir=DATA, resolution=resolution, data_format='rdir'),
)

controllers = dict(
    RunningLogger=dict(every_n_iters=10),
    Snapshoter=dict(every_n_iters=500, first_iter=True, num=200),
    FIDEvaluator=dict(every_n_iters=5000, first_iter=True, num=50000),
    Checkpointer=dict(every_n_iters=5000, first_iter=True),
)

modules = dict(
    discriminator=dict(
        model=dict(gan_type=gan_type, resolution=resolution),
        lr=dict(lr_type='FIXED'),
        opt=dict(opt_type='Adam', base_lr=1e-3, betas=(0.0, 0.99)),
        kwargs_train=dict(),
        kwargs_val=dict(),
    ),
    generator=dict(
        model=dict(gan_type=gan_type, resolution=resolution),
        lr=dict(lr_type='FIXED'),
        opt=dict(opt_type='Adam', base_lr=1e-3, betas=(0.0, 0.99)),
        kwargs_train=dict(w_moving_decay=0.995, style_mixing_prob=0.9,
                          trunc_psi=1.0, trunc_layers=0, randomize_noise=True),
        kwargs_val=dict(trunc_psi=1.0, trunc_layers=0, randomize_noise=False),
        g_smooth_img=10_000,
    )
)

loss = dict(
    type='LogisticGANLoss',
    d_loss_kwargs=dict(r1_gamma=10.0),
    g_loss_kwargs=dict(),
)
```

**Comment by ysig** [comment]
@ShenYujun Did you see my config? There is no `ProgressScheduler`.
Could you suggest which other lines I should comment, as I don't know?
If I could solve it by myself I wouldn't raise an issue.

**Comment by ShenYujun** [comment]
"try to comment out **_all_** codes related to `lod`". So, comment out Line 16, 34-36, 69-72 in `runners/stylegan_runner.py`. This should not be a hard-to-solve bug.

**Comment by ysig** [comment]
Ok I managed to make it run. For future users, this is the config I used:

```
# python3.7
"""Configuration for training StyleGAN on FF-HQ (1024) dataset.

All settings are particularly used for one replica (GPU), such as `batch_size`
and `num_workers`.
"""

runner_type = 'StyleGAN2Runner'
gan_type = 'stylegan2'
resolution = 512
batch_size = 2
val_batch_size = 2
total_img = 25000_000
num_gpus = 3
total_iters = int(total_img / (batch_size * num_gpus))

# Training dataset is repeated at the beginning to avoid loading dataset
# repeatedly at the end of each epoch. This can save some I/O time.
DATA = '/home/data'
data = dict(
    num_workers=4,
    repeat=1,
    train=dict(root_dir=DATA, resolution=resolution, mirror=0.5, data_format='rdir'),
    val=dict(root_dir=DATA, resolution=resolution, data_format='rdir'),
)

controllers = dict(
    RunningLogger=dict(every_n_iters=10),
    Snapshoter=dict(every_n_iters=500, first_iter=True, num=200),
    FIDEvaluator=dict(every_n_iters=5000, first_iter=True, num=50000),
    Checkpointer=dict(every_n_iters=5000, first_iter=True),
)

modules = dict(
    discriminator=dict(
        model=dict(gan_type=gan_type, resolution=resolution),
        lr=dict(lr_type='FIXED'),
        opt=dict(opt_type='Adam', base_lr=1e-3, betas=(0.0, 0.99)),
        kwargs_train=dict(),
        kwargs_val=dict(),
    ),
    generator=dict(
        model=dict(gan_type=gan_type, resolution=resolution),
        lr=dict(lr_type='FIXED'),
        opt=dict(opt_type='Adam', base_lr=1e-3, betas=(0.0, 0.99)),
        kwargs_train=dict(w_moving_decay=0.995, style_mixing_prob=0.9,
                          trunc_psi=1.0, trunc_layers=0, randomize_noise=True),
        kwargs_val=dict(trunc_psi=1.0, trunc_layers=0, randomize_noise=False),
        g_smooth_img=10_000,
    )
)

loss = dict(
    type='LogisticGANLoss',
    d_loss_kwargs=dict(r1_gamma=10.0),
    g_loss_kwargs=dict(),
)
```

I also changed `stylegan_runner.py` to:
```
# python3.7
"""Contains the runner for StyleGAN."""

from copy import deepcopy

from .base_gan_runner import BaseGANRunner

__all__ = ['StyleGANRunner', 'StyleGANRunner2']


class StyleGANRunner(BaseGANRunner):
    """Defines the runner for StyleGAN."""

    def __init__(self, config, logger):
        super().__init__(config, logger)
        self.lod = getattr(self, 'lod', None)

    def build_models(self):
        super().build_models()
        self.g_smooth_img = self.config.modules['generator'].get(
            'g_smooth_img', 10000)
        self.models['generator_smooth'] = deepcopy(self.models['generator'])

    def build_loss(self):
        super().build_loss()
        self.running_stats.add(
            f'Gs_beta', log_format='.4f', log_strategy='CURRENT')

    def train_step(self, data, **train_kwargs):
        # Set level-of-details.
        G = self.get_module(self.models['generator'])
        D = self.get_module(self.models['discriminator'])
        Gs = self.get_module(self.models['generator_smooth'])
        G.synthesis.lod.data.fill_(self.lod)
        D.lod.data.fill_(self.lod)
        Gs.synthesis.lod.data.fill_(self.lod)

        # Update discriminator.
        self.set_model_requires_grad('discriminator', True)
        self.set_model_requires_grad('generator', False)

        d_loss = self.loss.d_loss(self, data)
        self.optimizers['discriminator'].zero_grad()
        d_loss.backward()
        self.optimizers['discriminator'].step()

        # Life-long update for generator.
        beta = 0.5 ** (self.batch_size * self.world_size / self.g_smooth_img)
        self.running_stats.update({'Gs_beta': beta})
        self.moving_average_model(model=self.models['generator'],
                                  avg_model=self.models['generator_smooth'],
                                  beta=beta)

        # Update generator.
        if self._iter % self.config.get('D_repeats', 1) == 0:
            self.set_model_requires_grad('discriminator', False)
            self.set_model_requires_grad('generator', True)
            g_loss = self.loss.g_loss(self, data)
            self.optimizers['generator'].zero_grad()
            g_loss.backward()
            self.optimizers['generator'].step()

    def load(self, **kwargs):
        super().load(**kwargs)
        G = self.get_module(self.models['generator'])
        D = self.get_module(self.models['discriminator'])
        Gs = self.get_module(self.models['generator_smooth'])
        if kwargs['running_metadata']:
            lod = G.synthesis.lod.cpu().tolist()
            assert lod == D.lod.cpu().tolist()
            assert lod == Gs.synthesis.lod.cpu().tolist()
            self.lod = lod

class StyleGAN2Runner(BaseGANRunner):
    """Defines the runner for StyleGAN."""

    def __init__(self, config, logger):
        super().__init__(config, logger)
        self.lod = getattr(self, 'lod', 0)

    def build_models(self):
        super().build_models()
        self.g_smooth_img = self.config.modules['generator'].get(
            'g_smooth_img', 10000)
        self.models['generator_smooth'] = deepcopy(self.models['generator'])

    def build_loss(self):
        super().build_loss()
        self.running_stats.add(
            f'Gs_beta', log_format='.4f', log_strategy='CURRENT')

    def train_step(self, data, **train_kwargs):
        # Set level-of-details.
        G = self.get_module(self.models['generator'])
        D = self.get_module(self.models['discriminator'])
        Gs = self.get_module(self.models['generator_smooth'])

        # Update discriminator.
        self.set_model_requires_grad('discriminator', True)
        self.set_model_requires_grad('generator', False)

        d_loss = self.loss.d_loss(self, data)
        self.optimizers['discriminator'].zero_grad()
        d_loss.backward()
        self.optimizers['discriminator'].step()

        # Life-long update for generator.
        beta = 0.5 ** (self.batch_size * self.world_size / self.g_smooth_img)
        self.running_stats.update({'Gs_beta': beta})
        self.moving_average_model(model=self.models['generator'],
                                  avg_model=self.models['generator_smooth'],
                                  beta=beta)

        # Update generator.
        if self._iter % self.config.get('D_repeats', 1) == 0:
            self.set_model_requires_grad('discriminator', False)
            self.set_model_requires_grad('generator', True)
            g_loss = self.loss.g_loss(self, data)
            self.optimizers['generator'].zero_grad()
            g_loss.backward()
            self.optimizers['generator'].step()

    def load(self, **kwargs):
        super().load(**kwargs)
        G = self.get_module(self.models['generator'])
        D = self.get_module(self.models['discriminator'])
        Gs = self.get_module(self.models['generator_smooth'])
```

and `__init__.py` on the `runners` dir to:

```
# python3.7
"""Collects all runners."""

from .stylegan_runner import StyleGANRunner, StyleGAN2Runner

__all__ = ['StyleGANRunner', 'StyleGAN2Runner']
```

**Comment by ozkilim** [comment]
^Thanks this worked very well for me!
