### ISSUE TITLE
error in running  train.py

### ISSUE THREAD

**Issue by caiqiuurn** [genforce/genforce#3]
**I use the torch-1.5.1  torchvision-0.6.0 cudatoolkit-10.1, but there still exits this error:
Can you give me some suggestions?**

[2020-10-16 16:19:08][INFO] Building models ...
[2020-10-16 16:19:09][INFO] Finish building models.
[2020-10-16 16:19:09][INFO] Building controllers ...
[2020-10-16 16:19:09][INFO] Progressive Schedule:
[2020-10-16 16:19:09][INFO]   Resolution    8 (lod 3): batch size  32 *  1, learning rate scale 1.0
[2020-10-16 16:19:09][INFO]   Resolution   16 (lod 2): batch size  16 *  1, learning rate scale 1.0
[2020-10-16 16:19:09][INFO]   Resolution   32 (lod 1): batch size   8 *  1, learning rate scale 1.0
[2020-10-16 16:19:09][INFO]   Resolution   64 (lod 0): batch size   4 *  1, learning rate scale 1.0
[2020-10-16 16:19:09][INFO] Finish building controllers.
[2020-10-16 16:19:09][INFO] Building `train` dataset ...
Traceback (most recent call last):
  File "./train.py", line 117, in <module>
    main()
  File "./train.py", line 113, in main
    runner.train()
  File "/home/cqr/genforce-master/runners/base_runner.py", line 269, in train
    self.build_dataset('train')
  File "/home/cqr/genforce-master/runners/base_runner.py", line 140, in build_dataset
    dataset = BaseDataset(**self.config.data[mode])
  File "/home/cqr/genforce-master/datasets/datasets.py", line 175, in __init__
    zip_file = ZipLoader.get_zipfile(self.root_dir)
  File "/home/cqr/genforce-master/datasets/datasets.py", line 38, in get_zipfile
    zip_files[file_path] = zipfile.ZipFile(file_path, 'r')
  File "/home/cqr/anaconda3/envs/genforce/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/demo.zip'
Traceback (most recent call last):
  File "/home/cqr/anaconda3/envs/genforce/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cqr/anaconda3/envs/genforce/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cqr/anaconda3/envs/genforce/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/cqr/anaconda3/envs/genforce/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/cqr/anaconda3/envs/genforce/bin/python', '-u', './train.py', '--local_rank=0', 'configs/stylegan_demo.py', '--work_dir', 'work_dirs/stylegan_demo', '--launcher=pytorch']' returned non-zero exit status 1.

**Comment by ShenYujun** [comment]
Seems like the dataset file cannot be found. You should prepare your own data before training.

**Comment by limbo0000** [comment]
Hi @caiqiuurn, you could use the 'stylegan_training_demo.sh' to download the demo.zip first or prepare your own data.
