### ISSUE TITLE
Resolution assert in progressive_resize_image

### ISSUE THREAD

**Issue by Aminullah6264** [genforce/genforce#37]
I am getting the following error in progressive_resize_image. I have printed my image. shape and size. I have attached my congig.json as well. 

[2022-11-21 11:32:51][INFO] Building controllers ...
[2022-11-21 11:32:51][INFO] Progressive Schedule:
[2022-11-21 11:32:51][INFO]   Resolution    8 (lod 5): batch size  32 *  1, learning rate scale 1.0
[2022-11-21 11:32:51][INFO]   Resolution   16 (lod 4): batch size  16 *  1, learning rate scale 1.0
[2022-11-21 11:32:51][INFO]   Resolution   32 (lod 3): batch size   8 *  1, learning rate scale 1.0
[2022-11-21 11:32:51][INFO]   Resolution   64 (lod 2): batch size   4 *  1, learning rate scale 1.0
[2022-11-21 11:32:51][INFO]   Resolution  128 (lod 1): batch size   4 *  1, learning rate scale 1.5
[2022-11-21 11:32:51][INFO]   Resolution  256 (lod 0): batch size   4 *  1, learning rate scale 2.0
[2022-11-21 11:32:52][INFO] Finish building controllers.
[2022-11-21 11:32:52][INFO] Building `train` dataset ...
[2022-11-21 11:32:57][INFO] Finish building `train` dataset.
[2022-11-21 11:32:57][INFO] Building loss function ...
[2022-11-21 11:32:57][INFO] Finish building loss function.

[2022-11-21 11:32:57][INFO] Start training.
[2022-11-21 11:32:57][INFO] Reset the optimizer state at iter 000001 (lod 5.000000).
[2022-11-21 11:32:57][INFO] Rebuild the dataset at iter 000001 (lod 5.000000).
(457, 640, 3) 256
(333, 500, 3) 256
(1024, 1024, 3) 256
(610, 1024, 3) 256
(640, 427, 3) 256
(225, 338, 3) 256
(500, 333, 3) 256
(591, 392, 3) 256
(480, 640, 3) 256
(457, 640, 3) 8
(470, 640, 3) 8
(640, 640, 3) 8
(519, 500, 3) 8
(685, 860, 3) 8
(309, 500, 3) 8
(374, 500, 3) 8
(332, 500, 3) 8
Traceback (most recent call last):
  File "./train.py", line 122, in <module>
    main()
  File "./train.py", line 118, in main
    runner.train()
  File "/nfs/hpc/share/ullaham/SailON/phase3/GAN/genforce/runners/base_runner.py", line 294, in train
    data_batch = next(self.train_loader)
  File "/nfs/hpc/share/ullaham/SailON/phase3/GAN/genforce/datasets/dataloaders.py", line 91, in __next__
    data = next(self.iter_loader)
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nfs/hpc/share/ullaham/SailON/phase3/GAN/genforce/datasets/datasets.py", line 227, in __getitem__
    image = progressive_resize_image(image, self.resolution)
  File "/nfs/hpc/share/ullaham/SailON/phase3/GAN/genforce/datasets/transforms.py", line 82, in progressive_resize_image
    assert height == width
AssertionError

Traceback (most recent call last):
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/nfs/stak/users/ullaham/hpc-share/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/nfs/stak/users/ullaham/hpc-share/anaconda3/bin/python', '-u', './train.py', '--local_rank=0', 'configs/stylegan_SVO.py', '--work_dir', 'work_dirs/stylegan_SVO_train', '--launcher=pytorch']' returned non-zero exit status 1.

{
    "runner_type": "StyleGANRunner",
    "gan_type": "stylegan",
    "resolution": 256,
    "batch_size": 4,
    "val_batch_size": 32,
    "total_img": 100000,
    "data": {
        "num_workers": 4,
        "repeat": 500,
        "train": {
            "root_dir": "data/SVO_train.zip",
            "data_format": "zip",
            "resolution": 256,
            "mirror": 0.5
        },
        "val": {
            "root_dir": "data/SVO_train.zip",
            "data_format": "zip",
            "resolution": 256
        }
    },
    "controllers": {
        "RunningLogger": {
            "every_n_iters": 10
        },
        "ProgressScheduler": {
            "every_n_iters": 1,
            "init_res": 8,
            "minibatch_repeats": 4,
            "lod_training_img": 600000,
            "lod_transition_img": 600000,
            "batch_size_schedule": {
                "res4": 64,
                "res8": 32,
                "res16": 16,
                "res32": 8
            }
        },
        "Snapshoter": {
            "every_n_iters": 500,
            "first_iter": true,
            "num": 200
        },
        "FIDEvaluator": {
            "every_n_iters": 5000,
            "first_iter": true,
            "num": 50000
        },
        "Checkpointer": {
            "every_n_iters": 5000,
            "first_iter": true
        }
    },
    "modules": {
        "discriminator": {
            "model": {
                "gan_type": "stylegan",
                "resolution": 256
            },
            "lr": {
                "lr_type": "FIXED"
            },
            "opt": {
                "opt_type": "Adam",
                "base_lr": 0.001,
                "betas": [
                    0.0,
                    0.99
                ]
            },
            "kwargs_train": {},
            "kwargs_val": {}
        },
        "generator": {
            "model": {
                "gan_type": "stylegan",
                "resolution": 256
            },
            "lr": {
                "lr_type": "FIXED"
            },
            "opt": {
                "opt_type": "Adam",
                "base_lr": 0.001,
                "betas": [
                    0.0,
                    0.99
                ]
            },
            "kwargs_train": {
                "w_moving_decay": 0.995,
                "style_mixing_prob": 0.9,
                "trunc_psi": 1.0,
                "trunc_layers": 0,
                "randomize_noise": true
            },
            "kwargs_val": {
                "trunc_psi": 1.0,
                "trunc_layers": 0,
                "randomize_noise": false
            },
            "g_smooth_img": 10000
        }
    },
    "loss": {
        "type": "LogisticGANLoss",
        "d_loss_kwargs": {
            "r1_gamma": 10.0
        },
        "g_loss_kwargs": {}
    },
    "work_dir": "work_dirs/stylegan_SVO_train",
    "resume_path": null,
    "weight_path": null,
    "seed": null,
    "launcher": "pytorch",
    "backend": "nccl",
    "cudnn_benchmark": true,
    "cudnn_deterministic": false,
    "is_distributed": true,
    "num_gpus": 1
}

**Comment by Aminullah6264** [comment]
I was able to solve the issue by just squaring the image before the assert line. 

    image = cv2.resize(image, (size, size),
                           interpolation=cv2.INTER_LINEAR)
