### ISSUE TITLE
Failure to convert StyleGAN2-ADA-PyTorch model

### ISSUE THREAD

**Issue by nightrain-vampire** [genforce/genforce#42]
I have the official model weight trained from  [NVlabs](https://github.com/NVlabs/stylegan2-ada-pytorch)，but when i want to convert it into genforce style，I encounter the issue as follow：
```
========================================
Loading source weights from `/data/user3/fewshot/stylegan2-ada-pytorch/training-runs/00000-retina-auto2-batch32/network-snapshot-004400.pkl` ...
Successfully loaded!
--------------------
Converting source weights (G) to target ...
Traceback (most recent call last):
  File "/data/user3/fewshot/genforce/convert_model.py", line 77, in <module>
    main()
  File "/data/user3/fewshot/genforce/convert_model.py", line 66, in main
    convert_stylegan2ada_pth_weight(src_weight_path=args.source_model_path,
  File "/data/user3/fewshot/genforce/converters/stylegan2ada_pth_converter.py", line 187, in convert_stylegan2ada_pth_weight
    assert tf_var_name in official_tf_to_pth_var_mapping
AssertionError
```
What happens? How can I solve it?

**Comment by nightrain-vampire** [comment]
> I have the official model weight trained from [NVlabs](https://github.com/NVlabs/stylegan2-ada-pytorch)，but when i want to convert it into genforce style，I encounter the issue as follow：
> 
> ```
> ========================================
> Loading source weights from `/data/user3/fewshot/stylegan2-ada-pytorch/training-runs/00000-retina-auto2-batch32/network-snapshot-004400.pkl` ...
> Successfully loaded!
> --------------------
> Converting source weights (G) to target ...
> Traceback (most recent call last):
>   File "/data/user3/fewshot/genforce/convert_model.py", line 77, in <module>
>     main()
>   File "/data/user3/fewshot/genforce/convert_model.py", line 66, in main
>     convert_stylegan2ada_pth_weight(src_weight_path=args.source_model_path,
>   File "/data/user3/fewshot/genforce/converters/stylegan2ada_pth_converter.py", line 187, in convert_stylegan2ada_pth_weight
>     assert tf_var_name in official_tf_to_pth_var_mapping
> AssertionError
> ```
> 
> What happens? How can I solve it?

I solved it! The problem lies in stylegan2ada_pth_converter.py; In the official NVlabs stylegan2-ada-pytorch, the mapping_layers is 2 in the auto config, but in stylegan2ada_pth_converter.py, the mapping_layers is 8 as default.
```
G = build_model(gan_type=GAN_TPYE,
                    module='generator',
                    resolution=resolution,
                    z_space_dim=z_space_dim,
                    w_space_dim=w_space_dim,
                    label_size=label_size,
                    repeat_w=repeat_w,
                    mapping_layers=2,
                    image_channels=image_channels)
```
```
Gs = build_model(gan_type=GAN_TPYE,
                     module='generator',
                     resolution=resolution,
                     z_space_dim=z_space_dim,
                     w_space_dim=w_space_dim,
                     label_size=label_size,
                     repeat_w=repeat_w,
                     mapping_layers=2,
                     image_channels=image_channels)
```
Now the converter runs successfully!
