### ISSUE TITLE
Is StyleGAN2 code provided in this repo fully tested?

### ISSUE THREAD

**Issue by lzhbrian** [genforce/genforce#7]
Hi, thanks for the repo!
Is StyleGAN2 code provided in this repo fully tested?
https://github.com/genforce/genforce/blob/master/models/stylegan2_generator.py
https://github.com/genforce/genforce/blob/master/models/stylegan2_discriminator.py
Thanks.

**Comment by justimyhxu** [comment]
We have devoted ourselves to CVPR.
We will release the stylegan2 training script recently.

**Comment by lzhbrian** [comment]
Thanks, good luck on your CVPR submission!

**Comment by hdjsjyl** [comment]
Hi Author, 
    Just want to ask whether the StyleGAN2 code provided can be used for the pre-trained model in Model_zoo. Could I only use the code for inference? Looking forward to the full release of StyleGAN2. Thank you!

**Comment by justimyhxu** [comment]
Now Genforce supports the inference for StyleGAN2. The training code will be released soon.

**Comment by swamiviv** [comment]
Big fan of the repo. Any update here re StyleGAN2 training code? Thanks.

**Comment by zhenglisec** [comment]
Also waiting for the stylegan2 training script !!!

**Comment by swyoon** [comment]
Thanks for the super cool repo. The training script for StyleGAN2 should be awesome. Also waiting for it!

**Comment by mxl1990** [comment]
I try to train a StyleGAN2 using your scripts, but find following error:
`Traceback (most recent call last):
  File "./train.py", line 123, in <module>
    main()
  File "./train.py", line 119, in main
    runner.train()
  File "/home/lixiao/stylegan2-reid/runners/base_runner.py", line 300, in train
    self.train_step(data_batch, **train_kwargs)
  File "/home/lixiao/stylegan2-reid/runners/stylegan_runner.py", line 34, in train_step
    G.synthesis.lod.data.fill_(self.lod)
  File "/home/lixiao/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'SynthesisModule' object has no attribute 'lod'
`
So I am wondering that you update your scripts such as stylegan2_generator。
